### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by AlC4pwn** [Northfear/fheroes2-vita#1]
I've done a complete wipe and full reinstall but there is no default cfg file in  "ux0:app/FHOMM0002/" as mentioned on the main page. If no cfg is present it does seem to create one on launch (although on that initial launch it hangs at a black screen after selecting the resolution; reopening the game works normally)

But I've noticed in the cfg file created "Debug Mode" is set to 5460, is this correct or should it be set to 0?

**Comment by Northfear** [comment]
Hey
I should update the readme, thanks for reminding me. There's no default cfg now and default upstream auto generated config should work fine with Vita.
Game restart is required after resolution change indeed. Unfortunately nothing can be done about it right now.
Debug mode is totally weird tho. Could you try removing config file check it again?
It was always set to 0 by default for me.

**Comment by AlC4pwn** [comment]
Sorry for the delay, I didn't get any notification. For some reason I was getting 5460 but now it finally is being created with debug = 0. I'm very perplexed by what could possibly have caused it. Thanks for responding.
