### ISSUE TITLE
Audio tracks

### ISSUE THREAD

**Issue by J013k** [Northfear/fheroes2-vita#2]
How should I named audio tracks in ogg?

I mean I ripped audio tracks to ogg, but I am not sure how to named them.
Here is what I currently have:
![https://i.postimg.cc/yxDrYzSx/fheroes2.png](https://i.postimg.cc/yxDrYzSx/fheroes2.png)
Unfortunately I do not have any music.
I copied these files into `ux0:data/fheroes2/music/`.
I settings (`fheroes2.cfg`) I set `music = external`.

**Comment by Northfear** [comment]
Hey. Try this list:
```
homm2_01.ogg  homm2_10.ogg  homm2_19.ogg  homm2_28.ogg  homm2_37.ogg
homm2_02.ogg  homm2_11.ogg  homm2_20.ogg  homm2_29.ogg  homm2_38.ogg
homm2_03.ogg  homm2_12.ogg  homm2_21.ogg  homm2_30.ogg  homm2_39.ogg
homm2_04.ogg  homm2_13.ogg  homm2_22.ogg  homm2_31.ogg  homm2_40.ogg
homm2_05.ogg  homm2_14.ogg  homm2_23.ogg  homm2_32.ogg  homm2_41.ogg
homm2_06.ogg  homm2_15.ogg  homm2_24.ogg  homm2_33.ogg  homm2_42.ogg
homm2_07.ogg  homm2_16.ogg  homm2_25.ogg  homm2_34.ogg
homm2_08.ogg  homm2_17.ogg  homm2_26.ogg  homm2_35.ogg
homm2_09.ogg  homm2_18.ogg  homm2_27.ogg  homm2_36.ogg
```

Basically track02 should become homm2_01.ogg, track03 should become homm2_02.ogg etc..

**Comment by J013k** [comment]
Unfortunately I do not have music in the main menu, etc.

I copied all these files into `ux0:data/fheroes2/Music/`, tried also `ux0:data/fheroes2/music/`:
![https://i.postimg.cc/CLFHSrJv/fheroes2a.png](https://i.postimg.cc/CLFHSrJv/fheroes2a.png)
These ogg files have 112 KBPS 44kHz Stereo.

**Comment by Northfear** [comment]
Could you send me homm2_41.ogg, so I could test it myself?

**Comment by J013k** [comment]
BTW I have Windows not the DOS version.

**Comment by Northfear** [comment]
Both files are actually working fine for me.
Try deleting fheroes2.cfg and running the game again. Default config should work with ogg music.

**Comment by J013k** [comment]
Did you check DOS or Windows version?

Maybe there is something wrong with my files structure?
Here is how it looks like:
- fheroes2 (all folders are in lower cause, I also deleted `fheroes2.cfg`):
![https://i.postimg.cc/x8SjDKNh/root.png](https://i.postimg.cc/x8SjDKNh/root.png)
- anim:
![https://i.postimg.cc/GmNCnkZK/anim.png](https://i.postimg.cc/GmNCnkZK/anim.png)
- data:
![https://i.postimg.cc/d1YgJnn2/data.png](https://i.postimg.cc/d1YgJnn2/data.png)
- files:
![https://i.postimg.cc/8cCKCYv6/files.png](https://i.postimg.cc/8cCKCYv6/files.png)
- games:
![https://i.postimg.cc/XJ1KsYZr/games.png](https://i.postimg.cc/XJ1KsYZr/games.png)
- maps:
![https://i.postimg.cc/2Sd4PwbR/maps.png](https://i.postimg.cc/2Sd4PwbR/maps.png)
- music:
![https://i.postimg.cc/65njpC2z/music.png](https://i.postimg.cc/65njpC2z/music.png)

**Comment by J013k** [comment]
I was using initial version `0.8.1-vita.1`...
When I install `0.8.3-vita.2`I finally have got music.
