### ISSUE TITLE
Add Polish font

### ISSUE THREAD

**Issue by J013k** [Northfear/fheroes2-vita#3]
Is there a way to add Polish font?
I mean letters like `Ą ą Ć ć Ę ę Ł ł Ń ń Ó ó Ś ś Ź ź Ż ż`.

Currently I have missing signs or strange artifacts: 
![https://i.postimg.cc/br8SPGZC/New-game.jpg](https://i.postimg.cc/br8SPGZC/New-game.jpg)
![https://i.postimg.cc/0yrfF3R6/Start.jpg](https://i.postimg.cc/0yrfF3R6/Start.jpg)

I also have a problem with translation.
Some things are in Polish, some in English:
![https://i.postimg.cc/L847XNdR/PL-ENG.jpg](https://i.postimg.cc/L847XNdR/PL-ENG.jpg)

BTW When I initially start game (without `fheroes2.cfg`), I am asked to choose resolution:
![https://i.postimg.cc/1zB3FWXH/Resolution.jpg](https://i.postimg.cc/1zB3FWXH/Resolution.jpg)
When I choose 966x544 and "hit" OK, I'm getting BSOD:
![https://i.postimg.cc/GtG24byB/BSOD.jpg](https://i.postimg.cc/GtG24byB/BSOD.jpg)

I need to close and re-launch the game to be able to play.

**Comment by Northfear** [comment]
>Is there a way to add Polish font?

Not right now. Localization is not supported at the moment and you should probably ask upstream devs about it (I'm pretty sure that they already have an opened issue about it)
https://github.com/ihhub/fheroes2

>When I choose 966x544 and "hit" OK, I'm getting BSOD:

Yup, that's not supported ATM. There's a chance that it will be fixed in the next release tho.

**Comment by J013k** [comment]
Thanks.

I have added an issue in upstream build:
https://github.com/ihhub/fheroes2/issues/2453.

**Comment by J013k** [comment]
> Yup, that's not supported ATM. There's a chance that it will be fixed in the next release tho.

Thanks for fixing this issue in version 0.8.4-vita.2.

> Not right now. Localization is not supported at the moment and you should probably ask upstream devs about it (I'm pretty sure that they already have an opened issue about it)
> https://github.com/ihhub/fheroes2

Support for translation should be added in ver 1.0...
Do you think this issue should be closed or for now leave it as it is?

**Comment by Northfear** [comment]
Yeah, I'm closing this for now. Once there's upstream localization support, it should work on vita w/o any problems.
