### ISSUE TITLE
Missing FMVs

### ISSUE THREAD

**Issue by J013k** [Northfear/fheroes2-vita#4]
I do not have any ingame cinematics ([FMV](https://en.wikipedia.org/wiki/Full_motion_video)), nor at the beginning
or at the start of a new campaign.
I have copied `anim` folder from my CD into `ux0:data/fheroes2/heroes2/`.

Normally I have these [FMV](https://en.wikipedia.org/wiki/Full_motion_video) on my Windows version of a game:
![https://i.postimg.cc/Gh63BrkY/FMV1.png](https://i.postimg.cc/Gh63BrkY/FMV1.png)
![https://i.postimg.cc/yNy7rZ2X/FMV2.png](https://i.postimg.cc/yNy7rZ2X/FMV2.png)

Here is a video how it should looks like when game has been launched:
https://www.youtube.com/watch?v=OKRNZimOGlA.

**Comment by Northfear** [comment]
Intro video should be named H2XINTRO.SMK and yes, it should be inside "ux0:data/fheroes2/heroes2/anim" folder.
Only the video from the second screenshot should be played right now. Other ones are not supported (if I'm not mistaken).

**Comment by J013k** [comment]
I have this file, but I do not have any FMV at start:
![https://i.postimg.cc/hGVMLW7L/My-heroes.png](https://i.postimg.cc/hGVMLW7L/My-heroes.png)

**Comment by Northfear** [comment]
Can you send me H2XINTRO.SMK so I could check it out myself please?

**Comment by J013k** [comment]
Please read the `Rename` file.

**Comment by Northfear** [comment]
I can't really reproduce it. SMK file from this version seems to be different from the GoG one, but video still plays w/o any problems for me. Have you tried it with windows/linux version of fheroes2?

**Comment by J013k** [comment]
I tried version 0.8.4 (23 December 2020):
`fheroes2_windows_x64_SDL1`
`fheroes2_windows_x64_SDL2`
None of these versions launch FMVs...

Only when I insert a CD and launch org launcher `Heroes2w.exe` everything is fine.
So it is probably an upstream problem.

**Comment by J013k** [comment]
Sorry for this.
I copied all the FMVs into `ux0:data/fheroes2/Anim/`
instead of `ux0:data/fheroes2/heroes2/anim`.
