### ISSUE TITLE
Missing music after starting new campaign.

### ISSUE THREAD

**Issue by J013k** [Northfear/fheroes2-vita#5]
I do not know if my version of a game is causing problems,
but after staring new campaign I have a problem with music.
I mean I do **not** have any music.
I need to quit from the game, re-launch it, load save game.

**Comment by Northfear** [comment]
Can confirm (And it works well on Linux for me). I'll try looking into it once I'll have some free time.

**Comment by Mikrdk** [comment]
I confirm this issue as well. Quiting game, open up again, load game fixed it.

**Comment by Northfear** [comment]
Should be fixed in 0.9
https://github.com/Northfear/fheroes2-vita/releases

**Comment by Mikrdk** [comment]
Great, I can test tonight to confirm. Just to be certain: Can I just run new VPK for update? No files to be deleted or anything else to be mindful of?

**Comment by Northfear** [comment]
Yeah, simple VPK update should work fine

**Comment by J013k** [comment]
Fixed in 0.9.0-vita.2.
