### ISSUE TITLE
Controller pointer speed

### ISSUE THREAD

**Issue by J013k** [Northfear/fheroes2-vita#6]
Changing "Controller pointer speed" in cfg does not do anything...
I mean it does not matter if I select value 90 or 30, the cursor sensitivity will be the same:
![https://i.postimg.cc/VN0jYVP7/2021-02-05-071258.jpg](https://i.postimg.cc/VN0jYVP7/2021-02-05-071258.jpg)

At least in ver 0.9.0-vita.2.

**Comment by Northfear** [comment]
My bad. Changing it to "controller_pointer_speed" (with underscores) should work for now.
Underscores will be removed in the next update tho

**Comment by J013k** [comment]
Thanks.
This temporary workaround (`controller_pointer_speed`) seems to work:
![https://i.postimg.cc/vmVzFyFx/2021-02-05-114246.jpg](https://i.postimg.cc/vmVzFyFx/2021-02-05-114246.jpg)

**Comment by Northfear** [comment]
Fixed in 0.9.1, so I'm closing this one
