### ISSUE TITLE
[question] Support for new versions in this fork?

### ISSUE THREAD

**Issue by J013k** [Northfear/fheroes2-vita#7]
I have noticed that the main repo since 04\04\2021 finally has support for the PS Vita.

Does this mean that there won't be any new versions in here?

**Comment by Northfear** [comment]
Main fheroes2 repo is probably the best place for getting new version now.
I might release something here if upstream version will break Vita support or if I'll have some cool new functionality added. But for now there's no point of releasing the same thing twice.

PS. I've enabled discussions in this repo in case of any questions/suggestions concerning Vita support, etc.
