### ISSUE TITLE
[Question] New versions for Vita?

### ISSUE THREAD

**Issue by J013k** [Northfear/fheroes2-vita#8]
I have notice that version 0.9.4 came out...
Are there any plans for a Vita port?

**Comment by Northfear** [comment]
I've updated it on vitadb yesterday
https://vitadb.rinnegatamante.it/#/info/354
Build system has to be changed upstream, but unfortunately I have absolutely no time to look into that, so maybe I'll switch to old school builds after 0.9.5
PS. 0.9.4 is pretty cool BTW. With PoL campaign and all that

**Comment by J013k** [comment]
Thank you for the answer.
