### ISSUE TITLE
Missing Polish letters.

### ISSUE THREAD

**Issue by J013k** [Northfear/fheroes2-vita#9]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

PlayStation Vita

### Describe the bug

Is there a way to add Polish letters for the PS Vita port?
I mean letters like `Ą ą Ć ć Ę ę Ł ł Ń ń Ó ó Ś ś Ź ź Ż ż`.

* Here is how it looks like in Windows version (all letters are ok):
![https://i.postimg.cc/xTfJhmsz/win-43.png](https://i.postimg.cc/xTfJhmsz/win-43.png)
![https://i.postimg.cc/sXPx0f7m/win-33.png](https://i.postimg.cc/sXPx0f7m/win-33.png)
![https://i.postimg.cc/L6QXWbYc/win-53.png](https://i.postimg.cc/L6QXWbYc/win-53.png)

* Here is how it looks like in Vita port:
![https://i.postimg.cc/T3vSTRDg/jez1.png](https://i.postimg.cc/T3vSTRDg/jez1.png)
![https://i.postimg.cc/sgcR8BNv/jez2.png](https://i.postimg.cc/sgcR8BNv/jez2.png)
![https://i.postimg.cc/zf2Yzs5N/jez3.png](https://i.postimg.cc/zf2Yzs5N/jez3.png)

### Save file

Not needed.

**Comment by Northfear** [comment]
Including them in VPK file is probably a better idea. I might look into it

**Comment by J013k** [comment]
Sorry. I forgot to overwrite files from `.../files/lang`.
